config/routes.rb
Devjuic::Application.routes.draw do
  devise_for :guests

  resources :customers

  resources :experiments
  resources :posts

  devise_for :users

  root to: 'static_pages#index'

  match '/frequencies', to: 'frequencies#index'
  post '/frequencies/create', to: 'frequencies#create'
  post '/frequencies/check', to: 'frequencies#check'

  match '/lab', to: 'static_pages#lab'
  match '/store', to: 'store#index'
  match '/contact', to: 'static_pages#contact'
  match '/characters', to: 'characters#index'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  
  attr_accessible :description, :index_link, :title
  belongs_to :user

  def author
  	user
  end

  def author_name
  	author.first_name + ' ' + author.last_name
  end

  def day_created
  	created_at.strftime("%B %d, %Y")
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        current_user.experiments << @experiment
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :index_link %><br />
    <%= f.text_field :index_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<% @experiments.each do |experiment| %>
  <div class="row post-overview">
    <div class="span1">
      <%= gravatar_for experiment.author %>
     
    </div>
    <div class="span10">
      <h3><a href="<%= experiment.index_link %>"><%= experiment.title %></a></h3>
      <h5><%= experiment.description %></h5>
        <p>
          Created by <span class="gray"><%= experiment.author_name %></span> 
          on <span class="gray"><%= experiment.day_created %></span>
        </p>
    </div>

   
  </div>

<% end %>
<br/>

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @experiment.title %>
</p>

<p>
  <b>Description:</b>
  <%= @experiment.description %>
</p>

<p>
  <b>Index link:</b>
  <%= @experiment.index_link %>
</p>


<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to "Delete", @experiment, method: :delete, confirm: "Are you sure?", title: @experiment.title %> |
<%= link_to 'Back', experiments_path %>