config/routes.rb
Devjuic::Application.routes.draw do
  devise_for :guests

  resources :customers

  resources :experiments
  resources :posts

  devise_for :users

  root to: 'static_pages#index'

  match '/frequencies', to: 'frequencies#index'
  post '/frequencies/create', to: 'frequencies#create'
  post '/frequencies/check', to: 'frequencies#check'

  match '/lab', to: 'static_pages#lab'
  match '/store', to: 'store#index'
  match '/contact', to: 'static_pages#contact'
  match '/characters', to: 'characters#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to image_tag("devjuicLogo.png"), '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Lab", experiments_path %></li>
					<li><%= link_to "Blog", posts_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<% if user_signed_in? %>
						<li><a href="#">Hello, <%= current_user.first_name %></a></li>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Login", new_user_session_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devjuic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>